### ISSUE TITLE
The "Deliver" function does not work. 

### ISSUE THREAD

**Issue by Noelwong** [IBM/global-financing-blockchain#19]
Following the instructions in the README leads to this error when executing the "Delivered" button in shipper. 

![image](https://user-images.githubusercontent.com/35700900/79978665-daf96f00-84d2-11ea-9a68-525b199aa76e.png)
![image](https://user-images.githubusercontent.com/35700900/79978771-0714f000-84d3-11ea-8535-5c2d07a591de.png)
![image](https://user-images.githubusercontent.com/35700900/79978844-26ac1880-84d3-11ea-9442-2eaf4e05829b.png)

```
error: [Transaction]: _validatePeerResponses: No valid responses from any peers. 1 peer error responses:
    peer=peer0.org1.example.com, status=500, message=transaction returned with failure: Error: order status not shipping requested or delivering
Error processing transaction. Error: No valid responses from any peers. 1 peer error responses:
    peer=peer0.org1.example.com, status=500, message=transaction returned with failure: Error: order status not shipping requested or delivering
Error: No valid responses from any peers. 1 peer error responses:
    peer=peer0.org1.example.com, status=500, message=transaction returned with failure: Error: order status not shipping requested or delivering
    at Transaction._validatePeerResponses (/Users/hoklamwong/Documents/global-financing-blockchain-master/web-app/node_modules/fabric-network/lib/transaction.js:276:10)
    at Transaction.submit (/Users/hoklamwong/Documents/global-financing-blockchain-master/web-app/node_modules/fabric-network/lib/transaction.js:189:34)
    at <anonymous>
```

Node v8.12.0
npm v6.4.1
OSX Catalina 10.15.2
VSCode 1.39.0
docker-compose version 1.25.4, build 8d51620a
Docker version 19.03.8, build afacb8b
go version go1.13.6 darwin/amd64

**Comment by vladimirivkovic** [comment]
Second ```===``` should be replaced with ```==``` in this [line](https://github.com/IBM/global-financing-blockchain/blob/06e0505153de5b194d27d7e8f39d66eb9a2f22cf/contract/lib/globalFinance.js#L501).
Alternatively, you can remove ```JSON.stringify()``` around ```orderStatus.Delivering.code```.
